### ISSUE TITLE
async stdin

### ISSUE THREAD

**Issue by civilianatpoint** [davedoesdev/ffmpeg.js#4]
i checked  kagami,kukunin and your builds, nonee of u guys explain how to feed ffmpeg with async stdin. if it is not hard for you, can you build wasm or asm output for webm hls and show me how to feed ffmpeg with chunks please ? i can not build emscripten because of macos bullshit thats why i want ouput wasm or asm, and there is no single line code for async stdin chunk by chunk.

**Comment by davedoesdev** [comment]
@civilianatpoint take a look at https://github.com/davedoesdev/streamana which takes AV data, muxes it and feeds it to ffmpeg.
