### ISSUE TITLE
EVENT type HLS stream intermittent failure to upload/output last files

### ISSUE THREAD

**Issue by tawelton** [davedoesdev/ffmpeg.js#6]
Been fighting an issue the past couple weeks where the ffmpeg-hls-worker fails to upload the last segment of an HLS stream. In my experience there has been about a 50/50 chance that it successfully uploads the last segment and playlist file update, but it has been fairly unpredictable. This becomes a problem in scenarios like playing back a recorded HLS stream after the live stream has already ended (EVENT type in the HLS spec), since the player (e.g. video.js) can't locate the final segment which (sometimes) is listed in the playlist file, but never actually uploaded.

Here's some console output I captured to try and illustrate the problem. This was done by passing the `stream-end` event to the worker. To debug a bit, I switched from POSTing to a url, to instead using the `postMessage` option to pass the blobs back into the parent component so that I could gain more insight into what was actually being generated. The console log `MAKING REQUEST TO` is present in the original source code, while the others are my own. Should be able to see my attempts to log the output blob, the actual text contents of the playlist file, and then the calls to stop the recorder passing the data.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/24886918/171537336-e06d0ae4-c0b0-4f1c-94fc-843032f56309.png">

Although the `MAKING REQUEST TO` console log is output for segment 3 along with the corresponding playlist file update,  the actual segment and playlist blobs are never passed back to the parent before the ffexit/exit event is called.

As mentioned above, there are some situations where the playlist file blob is passed with the updated entry, but the segment never arrives. My guess here is that these final segment and playlist uploads are just not being properly waited for before closing, but I haven't been able to quite nail down why.

This could very well be an easy fix, but I have not been able to parse through all of what is going on within the `library-hls.js` file, where I assume this is all being managed. I also haven't been able to actually build the project for whatever reason, even using the docker container mentioned in #3. Haven't been able to tinker much with it due to that.

Would appreciate any guidance on how I may be misusing this or if there is any insight into why these final pieces might not be uploaded correctly

Love your work on this, VERY much needed upstream.

**Comment by tawelton** [comment]
As a quick follow up, here's an additional log that shows the situation where the playlist file is updated with a new segment, but the segment is never actually passed (upload4.ts)

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/24886918/171543440-244ac9db-f48d-4a33-82b0-f6f7a33cbc42.png">

**Comment by Lampropoulosss** [comment]
Hello @tawelton
How did you build the project?
Could you possibly send the built files to my email? 

ioannis.lampropoulos05@gmail.com

**Comment by davedoesdev** [comment]
@tawelton looks like some race where the worker is exiting before the message gets sent back. I'll take a look but might not be for a while. Thanks for reporting the issue.

**Comment by davedoesdev** [comment]
@Lampropoulosss these instructions should work: https://github.com/davedoesdev/ffmpeg.js/issues/5#issuecomment-1186096175

The built files are here: https://github.com/davedoesdev/streamana/tree/main/site

**Comment by davedoesdev** [comment]
@tawelton the data is posted asynchronously so may arrive after the exit event. Are you terminating the worker as soon as you get the exit event?

**Comment by davedoesdev** [comment]
I wonder if we could have a count of outstanding fetch requests and only post `ffexit` once that count is 0.

I think when `emscripten_exit` is called, no more calls to `emscripten_close_async` should be made (it's called on program exit) so we shouldn't get any extra calls after that.

@tawelton what do you think?

**Comment by Lampropoulosss** [comment]
Also, I'd like to mention that I am just looking for the
ffmpeg-worker-mp4.js file*

**Comment by davedoesdev** [comment]
@Lampropoulosss I don't distribute any MP4 code because of potential patent issues.

**Comment by davedoesdev** [comment]
@tawelton should be fixed by https://github.com/davedoesdev/ffmpeg.js/commit/42191f5248d91b7e7b914bbaacd4d735f9e708df

Please let me know if you're still seeing this issue.

**Comment by tawelton** [comment]
@davedoesdev sorry for the late reply here, didn't have github notifications set up to send me an email for whatever reason.

I was terminating the worker immediately. The use case is a short video clip messaging app that live streamed while recording the clip.

This solution you've added is exactly what I had in mind, just couldn't get the project to build for whatever reason and therefore couldn't test out the idea in order to make the pull request.

Thanks for fixing that!

Compliments on this project, btw. Doing this without involving the SharedArrayBuffer headache (FFMPEG.wasm project) is awesome!

**Comment by Lampropoulosss** [comment]
Hello, I did try the project, it is much slower than the official ffmpeg.js project.
