### ISSUE TITLE
Build files using Emscripten

### ISSUE THREAD

**Issue by Lampropoulosss** [davedoesdev/ffmpeg.js#7]
Hello, I've been looking for the files built and ready to use on a project of mine since I don't have any experience at all with Emscripten.
Would it be possible to build them and upload them or tell me what could I do in order to build the files locally.
Specifically, I'm interested in using the worker versions.

I've been using the official ffmpeg.js version but I've been coming across a few issues and I'd like to try these out.

Respectfully,
John L.

**Comment by davedoesdev** [comment]
@Lampropoulosss take a look here: https://github.com/davedoesdev/streamana/tree/main/site

**Comment by Lampropoulosss** [comment]
I do not seem to be able to find the `ffmpeg-worker-mp4.js` file anywhere.
I apologize for the inconvenience

I can only see a `ffmpeg-worker-hls.js` file which just contains this:

`../ffmpeg.js/ffmpeg-worker-hls.js `

But in the ffmpeg.js directory I cant seem to be able to find the mp4 worker neither the hls worker. The files doesnt seem to be built actually.

**Comment by davedoesdev** [comment]
Yes, sorry, due to patent issues I don't distribute any MP4 code.

**Comment by Lampropoulosss** [comment]
I'll try build it myself, could I let you know about any issues I might face when building?

**Comment by davedoesdev** [comment]
Sure, please open any build issues you have
